### ISSUE TITLE
Download photos doesn't work anymore

### ISSUE THREAD

**Issue by AL9000** [Terralego/terra-opp#29]
```bash
django_1          | Internal Server Error: /api/viewpoints/3/zip-pictures
django_1          | Traceback (most recent call last):
django_1          |   File "/code/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1          |     response = get_response(request)
django_1          |   File "/code/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
django_1          |     response = self.process_exception_by_middleware(e, request)
django_1          |   File "/code/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
django_1          |     response = response.render()
django_1          |   File "/code/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
django_1          |     self.content = self.rendered_content
django_1          |   File "/code/venv/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
django_1          |     ret = renderer.render(self.data, accepted_media_type, context)
django_1          |   File "/code/lib/terra-opp/terra_opp/renderers.py", line 91, in render
django_1          |     os.path.basename(file.name),
django_1          | AttributeError: 'str' object has no attribute 'name'
```

I don't know why the data returned by the ViewpointZipPictures class does not contains all the pictures files in the renderer.

**Comment by AL9000** [comment]
It was in fact due to the ZipRenderer called on the OPTIONS request before doing the GET request. It was generating the error above.
